In [15]:
import pandas as pd

In [16]:
df= pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [17]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [18]:
pd.__version__

'3.0.6'

In [19]:
df.shape

(10000, 11)

In [20]:
df['fuel_type'].nunique()

3

In [21]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [22]:
df.fuel_efficiency_mpg.max()

np.float64(41.2)

In [23]:
df['horsepower'].median()

np.float64(254.0)

In [24]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [25]:
df['horsepoer']= df['horsepower'].fillna(df['horsepower'].mode()[0])

In [26]:
df['horsepower'].median()

np.float64(254.0)

In [27]:
import numpy as np

In [37]:
df_asia = df[df['origin'] == 'Asia']

In [38]:
df_asia = df_asia[['vehicle_weight', 'model_year']]

In [39]:
df_asia = df_asia.head(7)

In [40]:
df_asia

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [41]:
X = df_asia.to_numpy()

In [42]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [44]:
X.shape

(7, 2)

In [45]:
XTX = X.T @ X

In [46]:
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [47]:
XTX_inv = np.linalg.inv(XTX)

In [48]:
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [49]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [50]:
y.shape

(7,)

In [51]:
w = np.linalg.inv(X.T @ X) @ X.T @ y

In [52]:
w

array([0.13644777, 0.2327492 ])

In [53]:
w.sum()

np.float64(0.36919696904925486)